{"uid":"fd7b38fa0dca3bf3","name":"test_search_flights_1_stop_1___DEL____JFK____25_06_2024____2_Stop__","fullName":"testcases.test_searchflights.TestSearchAndVerifyFilter#test_search_flights_1_stop_1___DEL____JFK____25_06_2024____2_Stop__","historyId":"2f1d58db96134f6ceb319001d1ae0c59","time":{"start":1713139056517,"stop":1713139078021,"duration":21504},"status":"failed","statusMessage":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 6 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [1/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [2/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 3 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '2 Stop'\n+ 2 Stop\n\n-+ [3/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 4 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [4/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 5 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [5/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 6 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '2 Stop'\n+ 2 Stop\n\n-+ [6/6] +-","statusTrace":"self = <testcases.test_searchflights.TestSearchAndVerifyFilter testMethod=test_search_flights_1_stop_1___DEL____JFK____25_06_2024____2_Stop__>, goingfrom = 'DEL', goingto = 'JFK'\ndate = '25/06/2024', stops = '2 Stop'\n\n    @data(*Utils.read_data_from_csv(\"/Users/k-bhatt/PythonTestFrameworkDemo/testdata/tdatacsv.csv\"))\n    @unpack\n    def test_search_flights_1_stop(self,goingfrom, goingto, date, stops):\n        # Provide going from location\n        search_flight_result =  self.launchPage.searchFlights(goingfrom, goingto, date)\n    \n        # To handle dynamic scroll\n        # self.launchPage.page_scroll()\n        self.launchPage.wait_for_loading_indicator()\n        # self.launchPage.page_scroll_to_bottom()\n        self.launchPage.page_scroll()\n    \n        # Select the filter 1 stop\n        search_flight_result.filter_flights_by_stop(stops)\n    \n        # Verify that the filtered results show flights having only 1 stop\n        allstops = search_flight_result.get_search_flights_results()\n        self.log.info(len(allstops))\n    \n>       self.utilPage.assertListItemText(allstops, stops)\n\ntestcases/test_searchflights.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nutilities/utils.py:16: in assertListItemText\n    self.assert_all()\nenv/lib/python3.11/site-packages/softest/case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following 6 failures were found in \"wrapper\" (utilities.utils.Utils):\nE   +----------------------+----------------------+----------------------+\nE    Failure 1 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '2 Stops' != '2 Stop'\nE   - 2 Stops\nE   ?       -\nE   + 2 Stop\nE   \nE   \nE   -+ [1/6] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 2 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '2 Stops' != '2 Stop'\nE   - 2 Stops\nE   ?       -\nE   + 2 Stop\nE   \nE   \nE   -+ [2/6] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 3 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '' != '2 Stop'\nE   + 2 Stop\nE   \nE   -+ [3/6] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 4 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '2 Stops' != '2 Stop'\nE   - 2 Stops\nE   ?       -\nE   + 2 Stop\nE   \nE   \nE   -+ [4/6] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 5 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '2 Stops' != '2 Stop'\nE   - 2 Stops\nE   ?       -\nE   + 2 Stop\nE   \nE   \nE   -+ [5/6] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 6 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '' != '2 Stop'\nE   + 2 Stop\nE   \nE   -+ [6/6] +-","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"browser","time":{"start":1713139049589,"stop":1713139049590,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"setup","time":{"start":1713139049590,"stop":1713139056515,"duration":6925},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"url","time":{"start":1713139049590,"stop":1713139049590,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_unittest_setUpClass_fixture_TestSearchAndVerifyFilter","time":{"start":1713139049590,"stop":1713139049590,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"class_setup","time":{"start":1713139056516,"stop":1713139056516,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 6 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [1/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [2/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 3 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '2 Stop'\n+ 2 Stop\n\n-+ [3/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 4 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [4/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 5 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [5/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 6 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '2 Stop'\n+ 2 Stop\n\n-+ [6/6] +-","statusTrace":"self = <testcases.test_searchflights.TestSearchAndVerifyFilter testMethod=test_search_flights_1_stop_1___DEL____JFK____25_06_2024____2_Stop__>, goingfrom = 'DEL', goingto = 'JFK'\ndate = '25/06/2024', stops = '2 Stop'\n\n    @data(*Utils.read_data_from_csv(\"/Users/k-bhatt/PythonTestFrameworkDemo/testdata/tdatacsv.csv\"))\n    @unpack\n    def test_search_flights_1_stop(self,goingfrom, goingto, date, stops):\n        # Provide going from location\n        search_flight_result =  self.launchPage.searchFlights(goingfrom, goingto, date)\n    \n        # To handle dynamic scroll\n        # self.launchPage.page_scroll()\n        self.launchPage.wait_for_loading_indicator()\n        # self.launchPage.page_scroll_to_bottom()\n        self.launchPage.page_scroll()\n    \n        # Select the filter 1 stop\n        search_flight_result.filter_flights_by_stop(stops)\n    \n        # Verify that the filtered results show flights having only 1 stop\n        allstops = search_flight_result.get_search_flights_results()\n        self.log.info(len(allstops))\n    \n>       self.utilPage.assertListItemText(allstops, stops)\n\ntestcases/test_searchflights.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nutilities/utils.py:16: in assertListItemText\n    self.assert_all()\nenv/lib/python3.11/site-packages/softest/case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following 6 failures were found in \"wrapper\" (utilities.utils.Utils):\nE   +----------------------+----------------------+----------------------+\nE    Failure 1 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '2 Stops' != '2 Stop'\nE   - 2 Stops\nE   ?       -\nE   + 2 Stop\nE   \nE   \nE   -+ [1/6] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 2 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '2 Stops' != '2 Stop'\nE   - 2 Stops\nE   ?       -\nE   + 2 Stop\nE   \nE   \nE   -+ [2/6] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 3 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '' != '2 Stop'\nE   + 2 Stop\nE   \nE   -+ [3/6] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 4 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '2 Stops' != '2 Stop'\nE   - 2 Stops\nE   ?       -\nE   + 2 Stop\nE   \nE   \nE   -+ [4/6] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 5 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '2 Stops' != '2 Stop'\nE   - 2 Stops\nE   ?       -\nE   + 2 Stop\nE   \nE   \nE   -+ [5/6] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 6 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '' != '2 Stop'\nE   + 2 Stop\nE   \nE   -+ [6/6] +-","steps":[],"attachments":[{"uid":"8f1ba20f1bfcd7bb","name":"Screenshot on failure","source":"8f1ba20f1bfcd7bb.png","type":"image/png","size":267944},{"uid":"75f0da50e098840c","name":"log","source":"75f0da50e098840c.txt","type":"text/plain","size":329},{"uid":"9efe392b6c09c1c7","name":"stdout","source":"9efe392b6c09c1c7.txt","type":"text/plain","size":184}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"setup::0","time":{"start":1713139078179,"stop":1713139078302,"duration":123},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_unittest_setUpClass_fixture_TestSearchAndVerifyFilter::0","time":{"start":1713139219387,"stop":1713139219387,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('setup')"},{"name":"parentSuite","value":"testcases"},{"name":"suite","value":"test_searchflights"},{"name":"subSuite","value":"TestSearchAndVerifyFilter"},{"name":"host","value":"PC2368"},{"name":"thread","value":"87291-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testcases.test_searchflights"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["@pytest.mark.usefixtures('setup')"]},"source":"fd7b38fa0dca3bf3.json","parameterValues":[]}