{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Product defects","children":[{"name":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 6 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [1/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [2/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 3 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '2 Stop'\n+ 2 Stop\n\n-+ [3/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 4 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [4/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 5 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [5/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 6 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '2 Stop'\n+ 2 Stop\n\n-+ [6/6] +-","children":[{"name":"test_search_flights_1_stop_1___DEL____JFK____25_06_2024____2_Stop__","uid":"58d94d445745942c","parentUid":"d73948388ae8ad27fe01abb52649186f","status":"failed","time":{"start":1713296324095,"stop":1713296344098,"duration":20003},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"d73948388ae8ad27fe01abb52649186f"},{"name":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 2 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [1/2] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [2/2] +-","children":[{"name":"test_search_flights_1_stop_2___DEL____JFK____25_05_2024____1_Stop__","uid":"2c6c89d17a66c75c","parentUid":"ad1f405ff7f6d663228e11116a09f5fe","status":"failed","time":{"start":1713296349332,"stop":1713296368544,"duration":19212},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"ad1f405ff7f6d663228e11116a09f5fe"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"},{"name":"Test defects","children":[{"name":"selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <li class=\"\">...</li> is not clickable at point (556, 311). Other element would receive the click: <p class=\"ac_cityname\">...</p>\n  (Session info: chrome=123.0.6312.124)\nStacktrace:\n0   chromedriver                        0x00000001036970c8 chromedriver + 4595912\n1   chromedriver                        0x000000010368ee33 chromedriver + 4562483\n2   chromedriver                        0x000000010329239a chromedriver + 381850\n3   chromedriver                        0x00000001032e3181 chromedriver + 713089\n4   chromedriver                        0x00000001032e1093 chromedriver + 704659\n5   chromedriver                        0x00000001032de6f7 chromedriver + 694007\n6   chromedriver                        0x00000001032dda9c chromedriver + 690844\n7   chromedriver                        0x00000001032d090c chromedriver + 637196\n8   chromedriver                        0x00000001032fe142 chromedriver + 823618\n9   chromedriver                        0x00000001032d02b8 chromedriver + 635576\n10  chromedriver                        0x00000001032fe2fe chromedriver + 824062\n11  chromedriver                        0x000000010331e14d chromedriver + 954701\n12  chromedriver                        0x00000001032fdee3 chromedriver + 823011\n13  chromedriver                        0x00000001032cebe4 chromedriver + 629732\n14  chromedriver                        0x00000001032cf79e chromedriver + 632734\n15  chromedriver                        0x000000010365cfe2 chromedriver + 4358114\n16  chromedriver                        0x0000000103661c2d chromedriver + 4377645\n17  chromedriver                        0x00000001036615a3 chromedriver + 4375971\n18  chromedriver                        0x0000000103661ed5 chromedriver + 4378325\n19  chromedriver                        0x0000000103646a05 chromedriver + 4266501\n20  chromedriver                        0x000000010366225d chromedriver + 4379229\n21  chromedriver                        0x0000000103639050 chromedriver + 4210768\n22  chromedriver                        0x000000010367fa98 chromedriver + 4500120\n23  chromedriver                        0x000000010367fc11 chromedriver + 4500497\n24  chromedriver                        0x000000010368ea73 chromedriver + 4561523\n25  libsystem_pthread.dylib             0x00007ff816bfb18b _pthread_start + 99\n26  libsystem_pthread.dylib             0x00007ff816bf6ae3 thread_start + 15","children":[{"name":"test_search_flights_1_stop_4___DEL____BOM____25_12_2024____2_Stop__","uid":"1f441a52a8b05a4d","parentUid":"78054814149170e32d08759e8c6204c8","status":"broken","time":{"start":1713296407924,"stop":1713296413511,"duration":5587},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":[],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"78054814149170e32d08759e8c6204c8"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}