{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Product defects","children":[{"name":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 6 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [1/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [2/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 3 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '2 Stop'\n+ 2 Stop\n\n-+ [3/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 4 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [4/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 5 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [5/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 6 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '2 Stop'\n+ 2 Stop\n\n-+ [6/6] +-","children":[{"name":"test_search_flights_1_stop_1___DEL____JFK____25_06_2024____2_Stop__","uid":"8f7f3ae0631d7057","parentUid":"e382077639ab46b0033df63bf876cfe3","status":"failed","time":{"start":1713317588858,"stop":1713317677933,"duration":89075},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"e382077639ab46b0033df63bf876cfe3"},{"name":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 2 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stop(s)' != '2 Stop'\n- 2 Stop(s)\n?       ---\n+ 2 Stop\n\n\n-+ [1/2] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stop(s)' != '2 Stop'\n- 2 Stop(s)\n?       ---\n+ 2 Stop\n\n\n-+ [2/2] +-","children":[{"name":"test_search_flights_1_stop_4___DEL____BOM____25_12_2024____2_Stop__","uid":"389eddd91e0c9d8","parentUid":"aeaa136950c17249e57333fbf721b8bd","status":"failed","time":{"start":1713317817705,"stop":1713317852476,"duration":34771},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"aeaa136950c17249e57333fbf721b8bd"},{"name":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 2 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [1/2] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [2/2] +-","children":[{"name":"test_search_flights_1_stop_1___DEL____JFK____25_06_2024____1_Stop__","uid":"4ec357e27e38ba94","parentUid":"ad1f405ff7f6d663228e11116a09f5fe","status":"failed","time":{"start":1713318541087,"stop":1713318629347,"duration":88260},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":true,"parameters":[],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"ad1f405ff7f6d663228e11116a09f5fe"},{"name":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 8 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [1/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [2/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 3 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [3/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 4 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [4/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 5 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [5/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 6 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [6/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 7 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [7/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 8 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [8/8] +-","children":[{"name":"test_search_flights_1_stop_3___DEL____LHR____25_05_2024____1_Stop__","uid":"4500a42942bc08b0","parentUid":"56c4a123abd9a644cfdb70cb393145d8","status":"failed","time":{"start":1713318673225,"stop":1713318763606,"duration":90381},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":3,"retriesStatusChange":true,"parameters":[],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"56c4a123abd9a644cfdb70cb393145d8"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}]}