{"98ed5ec12d73e38ed229c556a72b8c0e":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4500a42942bc08b0","status":"failed","statusDetails":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 8 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [1/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [2/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 3 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [3/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 4 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [4/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 5 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [5/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 6 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [6/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 7 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [7/8] +-\n\n+----------------------+----------------------+----------------------+\n Failure 8 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [8/8] +-","time":{"start":1713318673225,"stop":1713318763606,"duration":90381}}]},"cb965b49d65ea300604de77642d2ac9b":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"389eddd91e0c9d8","status":"failed","statusDetails":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 2 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stop(s)' != '2 Stop'\n- 2 Stop(s)\n?       ---\n+ 2 Stop\n\n\n-+ [1/2] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stop(s)' != '2 Stop'\n- 2 Stop(s)\n?       ---\n+ 2 Stop\n\n\n-+ [2/2] +-","time":{"start":1713317817705,"stop":1713317852476,"duration":34771}}]},"bc14e10ec5ac8ada402109feddf8ac29":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4ec357e27e38ba94","status":"failed","statusDetails":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 2 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [1/2] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '1 Stop'\n+ 1 Stop\n\n-+ [2/2] +-","time":{"start":1713318541087,"stop":1713318629347,"duration":88260}}]},"fceb4d58dde1ffb7480a4863a80a8e0a":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"ca74cad75abd00f3","status":"passed","time":{"start":1713318768453,"stop":1713318804912,"duration":36459}}]},"ff11c8b6a1a3427075fdc4277133d960":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"160a9836176df208","status":"passed","time":{"start":1713318634493,"stop":1713318668114,"duration":33621}}]},"2f1d58db96134f6ceb319001d1ae0c59":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"8f7f3ae0631d7057","status":"failed","statusDetails":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 6 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [1/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [2/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 3 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '2 Stop'\n+ 2 Stop\n\n-+ [3/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 4 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [4/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 5 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stops' != '2 Stop'\n- 2 Stops\n?       -\n+ 2 Stop\n\n\n-+ [5/6] +-\n\n+----------------------+----------------------+----------------------+\n Failure 6 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '' != '2 Stop'\n+ 2 Stop\n\n-+ [6/6] +-","time":{"start":1713317588858,"stop":1713317677933,"duration":89075}}]}}